version: "3.7"
services:
  redis:
    image: redis:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.os == centos
#    configs:
#      - my_config
#      - my_other_config
#configs:
#  my_config:
#    file: ./my_config.txt
#  my_other_config:
#    external: true