version: '3.8'

services:
  web:
    image: ulrichnilsson/pythonapi:latest
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: mydatabase
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  db-data:
