# Use postgres/example user/password credentials
version: '3.7'

services:

  db:
    image: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 5
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 5
    ports:
      - 8300:8080