apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: confusion
  namespace: default
  labels:
    app: confusion
spec:
  selector:
    matchLabels:
      app: confusion
      namespace: default
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: confusion
    spec:
      containers:
      - name: confusion
        image: ulrichnilsson/confusion:latest
        ports:
        - containerPort: 80
      #imagePullPolicy: Always
