name: Build go Hello World
on:
  push:
    branches:
      - master
    paths:
      - '**/Build-go-hello-world.yml'
      - 'golang/HelloWorld'
  pull_request:
    branches:
      - master
    paths:
      - '**/Build-go-hello-world.yml'
      - 'golang/HelloWorld'

jobs:
  Build-Go-Hello-World:
    runs-on: ubuntu-latest
    env:
      working-directory: golang/HelloWorld

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1' # The Go version to download (if necessary) and use.
#    - run: go version

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        
    - name: Run build
      run: go build .
      working-directory: ${{env.working-directory}}

    - name: Run vet & lint
      run: |
        go vet .
        golint .