apiVersion: v1
kind: Service
metadata:
  name: utilityapi
  labels: 
    app: utilityapi
spec:
  ports:
  - name: tcp-metrics
    port: 80
    protocol: TCP
    targetPort: metrics
  selector:
    app: utilityapi
status:
  loadBalancer: {}
  