apiVersion: app/v1
kind: Deployment
metadata:
  name: utilitygui
spec:
  template:
    spec:
      containers:
        - name: utilitygui
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Localk8s