# This is a basic workflow to help you get started with Actions

name: Dotnet-UtilityAPI-Docker-Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/Dotnet-UtilityAPI-Docker-Image.yml"
      - "dotnet5/**"
  pull_request:
    branches: [ master ]
    paths:
      - ".github/workflows/Dotnet-UtilityAPI-Docker-Image.yml"
      - "dotnet5/**"
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: List files
        run: ls -la

      #- name: Check dotnet version on runner
      #  run: dotnet --version
      
      #- name: Build docker ARM
      #  run: docker build ./dotnet/UtilityAPI -f ./dotnet/UtilityAPI/Dockerfile -t ulrichnilsson/utilityapi

      #- name: Docker list images
      #  run: docker image ls
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ulrichnilsson/utilityapi
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./dotnet/UtilityAPI/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


          #docker push ulrichnilsson/utilitygui:latest