# This is a basic workflow to help you get started with Actions

name: Java-HelloWorld-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/Java-HelloWorld.yml"
      - "Java/HelloWorld/**"
  pull_request:
    branches: [ master ]
    paths:
      - ".github/workflows/Java-HelloWorld.yml"
      - "Java/HelloWorld/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Check java version on runner
        run: javac --version
      
      - name: Javac
        run: javac Java/HelloWorld/HelloWorld.java

      - name: List files
        run: ls -la

      - name: List docker version
        run: docker --version
