# This is a basic workflow to help you get started with Actions

name: UtilityGUI-Docker-Image-multi-arch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/UtilityGUI-Docker-Image-multi-arch.yml"
      - "dotnet5/**"
  pull_request:
    branches: [ master ]
    paths:
      - ".github/workflows/UtilityGUI-Docker-Image-multi-arch.yml"
      - "dotnet5/**"
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: List files
        run: ls -la

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ulrichnilsson/utilityapi
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./Angular/UtilityGUI/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ulrichnilsson/utilitygui:latest
          